### ISSUE TITLE
AI2 Companion app won't work with https

### ISSUE THREAD

**Issue by giangduong** [mecodia/appinventor-docker#2]
Hello,

Everything works fine if appinventor is running with http. How to make AI2 Companion app (Android) work with appinventor https?

Thanks,
Giang.

**Comment by toabi** [comment]
Never tried it, but if you set up certificates which the app trusts it might just work?

**Comment by giangduong** [comment]
What do you mean by "the app trusts it"? How to make it? Please clarify.

Thanks.

**Comment by toabi** [comment]
Ah, sorry misinterpreted your message. Quick googling shows that HTTPS for AI-Server is not just an easy thing to do: https://appinventor.mit.edu/explore/blogs/jeff/2022/03/25/why-no-https - sorry I can't help you further with this right now :)

**Comment by giangduong** [comment]
Why do you do this "blockly<->rendezvous connection from https to http"? I can see you have below lines of code in Dockerfile. 

# Change legacy rendezvous connection back to http
RUN sed -i -e "s/'https:\/\/'/'http:\/\/'/g" blocklyeditor/src/replmgr.js

**Comment by giangduong** [comment]
At the moment, i can see that https://appinventor.mit.edu/ is working fine with https. I also tested it with AI2 Companion app.

**Comment by toabi** [comment]
I can't remember exactly what I did 4 years ago. This was mostly trial+error until it somehow worked. If you find out a nice way how to run it with https I'm happy for a PR with changes/docs.

**Comment by giangduong** [comment]
I solved this issue.

You will need to build the latest version (for ex: v196 ) and rendezvous service must support both http and https. The cause is AI2 Companion app still connect to rendezvous service via http.

Thanks anyways.
