### ISSUE TITLE
Cannot build with the latest appinventor version

### ISSUE THREAD

**Issue by giangduong** [mecodia/appinventor-docker#3]
Hello,

I did set this appinventorserver.build.args.VERSION to v196 and build successfully. But when i check, it is still v185a.
I check by going to menu Help --> About. Take a look at the screenshot below.
<img width="575" alt="image" src="https://github.com/mecodia/appinventor-docker/assets/8393739/01cf9ace-1431-4022-a84c-d72d69ce581b">

Thanks,
Giang.

**Comment by toabi** [comment]
Hm, weird, I mean it will checkout the given tag prior to build in https://github.com/mecodia/appinventor-docker/blob/771e402c2123151f009bc883b6c83f1ac5921228/Dockerfile#L26

Also v185a-994-g15fb75… in git describe format means something like 994 commits after tag v185a on commit with hash 15fb754….  which matches this commit https://github.com/mit-cml/appinventor-sources/commit/15fb75465fc232bf3f8b74dc866d6799f6d03ed5

So it built the last version, just the displaying there is not using the latest tag information.

**Comment by giangduong** [comment]
Yes. I checked and agree that it builds the last version.

Thanks.
